# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'for_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SideMenu = QtWidgets.QFrame(self.centralwidget)
        self.SideMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SideMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SideMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SideMenu.setObjectName("SideMenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SideMenu)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SideMenuCon = QtWidgets.QFrame(self.SideMenu)
        self.SideMenuCon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SideMenuCon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SideMenuCon.setObjectName("SideMenuCon")
        self.portscanner = QtWidgets.QPushButton(self.SideMenuCon)
        self.portscanner.setGeometry(QtCore.QRect(30, 50, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.portscanner.setFont(font)
        self.portscanner.setCheckable(False)
        self.portscanner.setAutoDefault(False)
        self.portscanner.setDefault(False)
        self.portscanner.setObjectName("portscanner")
        self.scheduledscan = QtWidgets.QPushButton(self.SideMenuCon)
        self.scheduledscan.setGeometry(QtCore.QRect(30, 110, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.scheduledscan.setFont(font)
        self.scheduledscan.setObjectName("scheduledscan")
        self.services = QtWidgets.QPushButton(self.SideMenuCon)
        self.services.setGeometry(QtCore.QRect(30, 170, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.services.setFont(font)
        self.services.setObjectName("services")
        self.horizontalLayout_2.addWidget(self.SideMenuCon)
        self.horizontalLayout.addWidget(self.SideMenu)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(30, 40, 51, 16))
        self.label.setObjectName("label")
        self.range = QtWidgets.QCheckBox(self.frame_2)
        self.range.setGeometry(QtCore.QRect(30, 80, 70, 16))
        self.range.setObjectName("range")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(250, 80, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.scan = QtWidgets.QPushButton(self.frame_2)
        self.scan.setGeometry(QtCore.QRect(220, 140, 75, 23))
        self.scan.setObjectName("scan")
        self.targetIP = QtWidgets.QLineEdit(self.frame_2)
        self.targetIP.setGeometry(QtCore.QRect(100, 40, 121, 21))
        self.targetIP.setObjectName("targetIP")
        self.rangeStart = QtWidgets.QLineEdit(self.frame_2)
        self.rangeStart.setGeometry(QtCore.QRect(100, 80, 121, 21))
        self.rangeStart.setObjectName("rangeStart")
        self.rangeEnd = QtWidgets.QLineEdit(self.frame_2)
        self.rangeEnd.setGeometry(QtCore.QRect(280, 80, 121, 21))
        self.rangeEnd.setObjectName("rangeEnd")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setGeometry(QtCore.QRect(20, 200, 531, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.portscanner.setText(_translate("MainWindow", "PORT SCANNER"))
        self.scheduledscan.setText(_translate("MainWindow", "SCHEDULED SCAN"))
        self.services.setText(_translate("MainWindow", "SERVICES"))
        self.label.setText(_translate("MainWindow", "Target IP :"))
        self.range.setText(_translate("MainWindow", "Range"))
        self.label_2.setText(_translate("MainWindow", "to"))
        self.scan.setText(_translate("MainWindow", "SCAN"))
        self.label_3.setText(_translate("MainWindow", "OUTPUT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
